# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Journeys"

# A description of your site for meta tag, search engine results.
# Maybe look into a quote?
#   Haemin Sumin: Everything in this universe is evanescent
#   Haemin Sumin: Choose happiness, not success, as your life’s goal. If you become successful but aren’t happy, then what is the point?
#   Haemin Sumin: Any conversation can become interesting and lively as soon as we start speaking with real honesty.
#   Why I want to live alone: Haemin sumin Whether we like it or not, we naturally become influenced by our surroundings

description: "Unfiltered thoughts about experiences in our muddled lives"

#   Hamein Sumin: Do you want to be happy, or do you want to appear happy? Never mind what the world tells you to do to be happy. Be truthful to yourself and discover what you really want


# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://vanderdonckt.info"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "UA-161404151-1"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  # - text: Style Guide
  #   url: /style-guide/
  - text: Tags
    url: /tags
  # - text: Download
  #   url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#373d47'  # '#2d72d9'

# Site footer
footer:
  content: "&copy; Journeys all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate
  - jemoji

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
